export const PROVINCE_IMAGES = {
  'Buenos Aires':                       require('../../assets/provincias/buenos_aires.png'),
  'Catamarca':                          require('../../assets/provincias/catamarca.png'),
  'Chaco':                              require('../../assets/provincias/chaco.png'),
  'Chubut':                             require('../../assets/provincias/chubut.png'),
  'Ciudad Autónoma de Buenos Aires':    require('../../assets/provincias/ciudad_autonoma_de_buenos_aires.png'),
  'Córdoba':                            require('../../assets/provincias/cordoba.png'),
  'Corrientes':                         require('../../assets/provincias/corrientes.png'),
  'Entre Ríos':                         require('../../assets/provincias/entre_rios.png'),
  'Formosa':                            require('../../assets/provincias/formosa.png'),
  'Jujuy':                              require('../../assets/provincias/jujuy.png'),
  'La Pampa':                           require('../../assets/provincias/la_pampa.png'),
  'La Rioja':                           require('../../assets/provincias/la_rioja.png'),
  'Mendoza':                            require('../../assets/provincias/mendoza.png'),
  'Misiones':                           require('../../assets/provincias/misiones.png'),
  'Neuquén':                            require('../../assets/provincias/neuquen.png'),
  'Río Negro':                          require('../../assets/provincias/rio_negro.png'),
  'Salta':                              require('../../assets/provincias/salta.png'),
  'San Juan':                           require('../../assets/provincias/san_juan.png'),
  'San Luis':                           require('../../assets/provincias/san_luis.png'),
  'Santa Cruz':                         require('../../assets/provincias/santa_cruz.png'),
  'Santa Fe':                           require('../../assets/provincias/santa_fe.png'),
  'Santiago del Estero':                require('../../assets/provincias/santiago_del_estero.png'),
  'Tierra del Fuego':                   require('../../assets/provincias/tierra_del_fuego.png'),
  'Tucumán':                            require('../../assets/provincias/tucuman.png'),
};
